assume-role-example:
  image: 
    name: amazon/aws-cli:latest
    entrypoint: [""]
  script:
   - >
     STS=($(aws sts assume-role-with-web-identity
     --role-arn ${ROLE_ARN}
     --role-session-name "gitlab-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
     --web-identity-token ${CI_JOB_JWT_V2}
     --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
     --output text))      
   - export AWS_ACCESS_KEY_ID="${STS[0]}"
   - export AWS_SECRET_ACCESS_KEY="${STS[1]}"
   - export AWS_SESSION_TOKEN="${STS[2]}"
   - aws sts get-caller-identity
